<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RuntimeFrameworkVersion>10.0.12</RuntimeFrameworkVersion>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MorphocyteOS</AssemblyName>
    <RootNamespace>MorphocyteRouter</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\morphocyte.ico</ApplicationIcon>
    <Version>1.2.2</Version>
    <AssemblyVersion>1.2.2.0</AssemblyVersion>
    <FileVersion>1.2.2.0</FileVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Authors>MorphocyteOS</Authors>
    <Product>MorphocyteOS Router</Product>
    <Description>Локальный менеджер маршрутов Mihomo/Clash</Description>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Using Remove="System.Windows.Forms" />
    <Using Remove="System.Drawing" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />
    <Resource Include="Assets\morphocyte-icon.png" />
    <Resource Include="Assets\morphocyte.ico" />
    <EmbeddedResource Include="Assets\profile-template.yaml" LogicalName="MorphocyteOS.profile-template.yaml" />
  </ItemGroup>
</Project>
